name: Pylint

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"
#      displayName: "Build daily at 8 a.m."
#      branches:
#        include:
#          - main
#      always: true
  workflow_dispatch:
    inputs:
      dispatch:
        description: 'workflow dispatch msg'
        required: false
        default: 'Workflow Dispatch is run!'

jobs:
  workflow-dispatch:

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.dispatch }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest
          pip install psutil

  flake8-linting:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Automated Unit Tests
        run: |
          cd LF8/src/
          pytest test_Alarmsystem.py

